update justfile

diff --git a/common/justfile b/common/justfile
--- a/common/justfile
+++ b/common/justfile
@@ -1,147 +1,155 @@
 #!/usr/bin/env just --justfile
 
-# Environment variables read by this script
-xdg_config_home := env_var_or_default("XDG_CONFIG_HOME", "$HOME/.config")
-
-# Variables used in this script
-just_dir := justfile_directory()
-
-# Auto decide package manager
-pkg_install := if os() == "macos" {
-    "brew install"
-} else if path_exists("/usr/bin/pacman") == "true" {
-    "sudo pacman -S"
-} else {
-    "echo 'Unsupported OS or package manager' && exit 1;"
-}
-pkg_install_brew_cask := if os() == "macos" {
-    "brew install --cask"
-} else if path_exists("/usr/bin/pacman") == "true" {
-    "sudo pacman -S"
-} else {
-    "echo 'Unsupported OS or package manager' && exit 1;"
-}
+export CONFIG_DIR := justfile_directory()
+export XDG_CONFIG_HOME := env_var_or_default("XDG_CONFIG_HOME", env_var("HOME") + "/.config")
+aur_helper := `if command -v paru &> /dev/null; then echo "paru"; elif command -v yay &> /dev/null; then echo "yay"; else echo ""; fi`
+pkg_install := if os() == "macos" { `if command -v brew &> /dev/null; then echo "brew install"; else echo ""; fi` } else { `if command -v pacman &> /dev/null; then echo "sudo pacman -S"; else echo ""; fi` }
+pkg_install_brew_cask := if os() == "macos" { `if command -v brew &> /dev/null; then echo "brew install --cask"; else echo ""; fi` } else { `if command -v pacman &> /dev/null; then echo "sudo pacman -S"; else echo ""; fi` }
 
 # Help message
 help:
-    @echo "Prequisites for this script:"
+    @echo "Prerequisites for this script:"
     @echo "    - OS: MacOS or Arch Linux"
     @echo "    - For MacOS, homebrew installed"
-    @echo "This script reads the following environment variables:"
-    @echo "    XDG_CONFIG_HOME: The directory for user configuration files (default: $HOME/.config)"
     @just --list
 
+# Check if package manager (homebrew or pacman) is available
+_pkg_mgr:
+    #!/usr/bin/env bash
+    set -euo pipefail
+
+    if [ "{{ os() }}" = "macos" ]; then
+        # Check if homebrew is available
+        if ! command -v brew &> /dev/null; then
+            echo "[ERROR] homebrew not found"
+            exit 1
+        fi
+        echo "[OK] homebrew is available"
+    else
+        # Check if pacman is available
+        if ! command -v pacman &> /dev/null; then
+            echo "[ERROR] pacman not found"
+            exit 1
+        fi
+        echo "[OK] pacman is available"
+    fi
+
 # Install zsh (setup later)
-zsh-install:
+zsh-install: _pkg_mgr
     # Install zsh
-    {{pkg_install}} zsh
+    {{ pkg_install }} zsh
     # Install oh-my-zsh
     sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
 
 # Setup zsh after installation
-zsh-setup:
+zsh-setup: _pkg_mgr
     # Install plugins for oh-my-zsh
     git clone https://github.com/Aloxaf/fzf-tab ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/fzf-tab
     git clone https://github.com/zsh-users/zsh-autosuggestions.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
     git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting
     # Install fzf and zoxide
-    {{pkg_install}} fzf zoxide
+    {{ pkg_install }} fzf zoxide
     # Edit zprofile
-    echo "source {{just_dir}}/zsh/profile.zsh" >> ~/.zprofile
-    # Edit zshrc
-    echo "source {{just_dir}}/zsh/rc.zsh" > ~/.zshrc
+    echo "source $CONFIG_DIR/zsh/profile.zsh" >> ~/.zprofile
+    # Edit zshrc (overwrite)
+    echo "source $CONFIG_DIR/zsh/rc.zsh" > ~/.zshrc
     # Change login shell to zsh
     chsh -s $(which zsh)
 
 # Install kitty terminal emulator
-kitty-install:
+kitty-install: _pkg_mgr
     # Install kitty
-    {{pkg_install_brew_cask}} kitty
+    {{ pkg_install_brew_cask }} kitty
     # Symlink kitty configuration
-    mkdir -p {{xdg_config_home}}/kitty
-    ln -s {{just_dir}}/kitty/kitty.conf {{xdg_config_home}}/kitty/kitty.conf
+    mkdir -p $XDG_CONFIG_HOME/kitty
+    ln -s $CONFIG_DIR/kitty/kitty.conf $XDG_CONFIG_HOME/kitty/kitty.conf
 
 # Install theme for kitty
 kitty-theme:
     # Install catppuccin theme for kitty
-    kitten themes --dump-theme Catppuccin-Macchiato > {{xdg_config_home}}/kitty/Catppuccin-Macchiato.conf
+    kitten themes --dump-theme Catppuccin-Macchiato > $XDG_CONFIG_HOME/kitty/Catppuccin-Macchiato.conf
 
 # Install starship prompt
-starship:
+starship: _pkg_mgr
     # Install starship
-    {{pkg_install}} starship
+    {{ pkg_install }} starship
     # Symlink starship configuration
-    ln -s {{just_dir}}/starship/starship.toml {{xdg_config_home}}/starship.toml
+    ln -s $CONFIG_DIR/starship/starship.toml $XDG_CONFIG_HOME/starship.toml
+
+sevenzip_pkg := if os() == "macos" { "sevenzip" } else { "7zip" }
 
 # Install yazi
-yazi:
+yazi: _pkg_mgr
     # Install yazi
-    {{pkg_install}} yazi
+    {{ pkg_install }} yazi
+    # Install essential CLI tools used by yazi
+    {{ pkg_install }} ripgrep fd fzf zoxide jq poppler resvg {{ sevenzip_pkg }} imagemagick ffmpeg
     # Install plugins for yazi
     ya pkg add yazi-rs/plugins:git
-    # ya pkg add yazi-rs/plugins:max-preview
+    ya pkg add yazi-rs/plugins:max-preview
     ya pkg add KKV9/compress
     # Symlink yazi configuration
-    mkdir -p {{xdg_config_home}}/yazi
-    ln -s {{just_dir}}/yazi/init.lua {{xdg_config_home}}/yazi/init.lua
-    ln -s {{just_dir}}/yazi/yazi.toml {{xdg_config_home}}/yazi/yazi.toml
-    ln -s {{just_dir}}/yazi/keymap.toml {{xdg_config_home}}/yazi/keymap.toml
+    mkdir -p $XDG_CONFIG_HOME/yazi
+    ln -s $CONFIG_DIR/yazi/init.lua $XDG_CONFIG_HOME/yazi/init.lua
+    ln -s $CONFIG_DIR/yazi/yazi.toml $XDG_CONFIG_HOME/yazi/yazi.toml
+    ln -s $CONFIG_DIR/yazi/keymap.toml $XDG_CONFIG_HOME/yazi/keymap.toml
     # Install catppuccin theme for yazi
-    cd {{xdg_config_home}}/yazi && wget https://raw.githubusercontent.com/catppuccin/yazi/refs/heads/main/themes/macchiato/catppuccin-macchiato-blue.toml -O theme.toml
-    cd {{xdg_config_home}}/yazi && wget https://github.com/catppuccin/bat/blob/main/themes/Catppuccin%20Macchiato.tmTheme
+    cd $XDG_CONFIG_HOME/yazi && wget https://raw.githubusercontent.com/catppuccin/yazi/refs/heads/main/themes/macchiato/catppuccin-macchiato-blue.toml -O theme.toml
+    cd $XDG_CONFIG_HOME/yazi && wget https://github.com/catppuccin/bat/blob/main/themes/Catppuccin%20Macchiato.tmTheme
+
+nvim_pkg := if os() == "macos" { "neovim" } else { "nvim" }
 
 # Install neovim
-nvim_pkg := if os() == "macos" { "neovim" } else { "nvim" }
-neovim:
+neovim: _pkg_mgr
     # Install neovim
-    {{pkg_install}} {{nvim_pkg}}
+    {{ pkg_install }} {{ nvim_pkg }}
     # Install essential CLI tools for neovim
-    {{pkg_install}} ripgrep fd fzf
+    {{ pkg_install }} ripgrep fd fzf
     # Symlink neovim configuration
-    mkdir -p {{xdg_config_home}}/nvim
-    ln -s {{just_dir}}/nvim/init.lua {{xdg_config_home}}/nvim/init.lua
-    ln -s {{just_dir}}/nvim/lua {{xdg_config_home}}/nvim/lua
-    ln -s {{just_dir}}/nvim/snippets {{xdg_config_home}}/nvim/snippets
+    mkdir -p $XDG_CONFIG_HOME/nvim
+    ln -s $CONFIG_DIR/nvim/init.lua $XDG_CONFIG_HOME/nvim/init.lua
+    ln -s $CONFIG_DIR/nvim/lua $XDG_CONFIG_HOME/nvim/lua
+    ln -s $CONFIG_DIR/nvim/snippets $XDG_CONFIG_HOME/nvim/snippets
 
 # Install gitui
-gitui:
+gitui: _pkg_mgr
     # Install gitui
-    {{pkg_install}} gitui
+    {{ pkg_install }} gitui
     # Symlink gitui configuration
-    mkdir -p {{xdg_config_home}}/gitui
-    ln -s {{just_dir}}/gitui/key_bindings.ron {{xdg_config_home}}/gitui/key_bindings.ron
+    mkdir -p $XDG_CONFIG_HOME/gitui
+    ln -s $CONFIG_DIR/gitui/key_bindings.ron $XDG_CONFIG_HOME/gitui/key_bindings.ron
     # Install catppuccin theme for gitui
-    cd {{xdg_config_home}}/gitui && git clone https://github.com/catppuccin/gitui.git catppuccin && cp catppuccin/themes/catppuccin-macchiato.ron theme.ron && rm -rf catppuccin
+    cd $XDG_CONFIG_HOME/gitui && git clone https://github.com/catppuccin/gitui.git catppuccin && cp catppuccin/themes/catppuccin-macchiato.ron theme.ron && rm -rf catppuccin
 
 # Setup git
 git:
     # Symlink git configuration
-    ln -s {{just_dir}}/git/gitconfig-unix ~/.gitconfig
+    ln -s $CONFIG_DIR/git/gitconfig-unix ~/.gitconfig
     # For windows, manually create a symlink:
-    #   mklink %HOMEPATH%\.gitconfig {{just_dir}}\git\gitconfig-windows
+    #   mklink %HOMEPATH%\.gitconfig $CONFIG_DIR\git\gitconfig-windows
     # !!! IMPORTANT: Change user.name and user.email in ~/.gitconfig to your own values !!!
 
 # Install zellij
-zellij:
+zellij: _pkg_mgr
     # Install zellij
-    {{pkg_install}} zellij
+    {{ pkg_install }} zellij
     # Symlink zellij configuration
-    mkdir -p {{xdg_config_home}}/zellij
-    ln -s {{just_dir}}/zellij/config.kdl {{xdg_config_home}}/zellij/config.kdl
+    mkdir -p $XDG_CONFIG_HOME/zellij
+    ln -s $CONFIG_DIR/zellij/config.kdl $XDG_CONFIG_HOME/zellij/config.kdl
 
 # Install tmux
-tmux:
+tmux: _pkg_mgr
     # Install tmux
-    {{pkg_install}} tmux
+    {{ pkg_install }} tmux
     # Install tpm plugin manager for tmux
     git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
     # Install catppuccin theme for tmux
     git clone https://github.com/catppuccin/tmux ~/.tmux/plugins/catppuccin/tmux
     # Symlink tmux configuration
-    ln -s {{just_dir}}/tmux/tmux.conf ~/.tmux.conf
+    ln -s $CONFIG_DIR/tmux/tmux.conf ~/.tmux.conf
 
 # Install user scripts
 user-scripts:
     # Symlink user scripts to ~/.local/bin
     mkdir -p ~/.local/bin
-    for script in {{just_dir}}/scripts/*.sh; do ln -s $script ~/.local/bin/$(basename $script .sh); chmod u+x $script; done
+    for script in $CONFIG_DIR/scripts/*.sh; do ln -s $script ~/.local/bin/$(basename $script .sh); chmod u+x $script; done
diff --git a/linux/justfile b/linux/justfile
--- a/linux/justfile
+++ b/linux/justfile
@@ -1,31 +1,45 @@
 #!/usr/bin/env just --justfile
 
-# Environment variables read by this script
-aur_helper := env_var_or_default("AUR_HELPER", "paru")
-xdg_config_home := env_var_or_default("XDG_CONFIG_HOME", "$HOME/.config")
-
-# Variables used in this script
-just_dir := justfile_directory()
+export CONFIG_DIR := justfile_directory()
+export XDG_CONFIG_HOME := env_var_or_default("XDG_CONFIG_HOME", env_var("HOME") + "/.config")
+export XDG_DATA_HOME := env_var_or_default("XDG_DATA_HOME", env_var("HOME") + "/.local/share")
+aur_helper := `if command -v paru &> /dev/null; then echo "paru"; elif command -v yay &> /dev/null; then echo "yay"; else echo ""; fi`
 
 # Help message
 help:
-    @echo "Prequisites for this script:"
+    @echo "Prerequisites for this script:"
     @echo "    - Linux distribution: Arch Linux"
     @echo "    - AUR helper (paru, yay, etc.) installed"
-    @echo "This script reads the following environment variables:"
-    @echo "    AUR_HELPER: The AUR helper to use (default: paru)"
-    @echo "    XDG_CONFIG_HOME: The directory for user configuration files (default: $HOME/.config)"
     @just --list
 
+# Check if package managers (pacman and AUR helper) are available
+_pkg_mgr:
+    #!/usr/bin/env bash
+    set -euo pipefail
+
+    # Check if pacman is available
+    if ! command -v pacman &> /dev/null; then
+        echo "[ERROR] pacman not found"
+        exit 1
+    fi
+    echo "[OK] pacman is available"
+
+    # Check if AUR helper is available
+    if [ -z "{{ aur_helper }}" ]; then
+        echo "[ERROR] AUR helper not found"
+        exit 1
+    fi
+    echo "[OK] {{ aur_helper }} is available"
+
 # Create subdirectories in home directory
-create-home-dirs:
+home-dirs:
     # Conventional directories
     mkdir -p ~/Desktop ~/Downloads ~/Documents ~/Pictures ~/Videos ~/Music
     # Development directories
     mkdir -p ~/Projects
 
 # Install CLI tools
-cli-install:
+cli: _pkg_mgr
     # Alternatives to `cd`, `ls`, `cat`, `du`, `ps` and `top`
     sudo pacman -S zoxide eza bat dust procs bottom
     # Alternatives to `grep`, `find`, `sed` and `diff`
@@ -47,10 +61,10 @@ cli-install:
     sudo pacman -S tealdeer grex tokei hyperfine pastel
 
 # Install GUI applications
-app-install:
+app: _pkg_mgr
     # Web browser
     sudo pacman -S firefox
-    {{aur_helper}} -S zen-browser-bin
+    {{ aur_helper }} -S zen-browser-bin
     # File manager
     sudo pacman -S thunar
     # Text editor
@@ -58,7 +72,7 @@ app-install:
     # Download manager
     sudo pacman -S qbittorrent
     # Screenshot
-    {{aur_helper}} -S grim slurp grimblast-git
+    {{ aur_helper }} -S grim slurp grimblast-git
     # Video recording and streaming
     sudo pacman -S obs-studio
     # Image viewer
@@ -71,50 +85,50 @@ app-install:
     sudo pacman -S go-musicfox
     # WeChat
     # HiDPI scaling: https://github.com/hyprwm/hyprland/discussions/7923
-    {{aur_helper}} -S wechat-bin
+    {{ aur_helper }} -S wechat-bin
     # Office suite
-    {{aur_helper}} -S wps-office-cn wps-office-mui-zh-cn ttf-wps-fonts freetype2-wps
+    {{ aur_helper }} -S wps-office-cn wps-office-mui-zh-cn ttf-wps-fonts freetype2-wps
     # Note taking
     sudo pacman -S obsidian
 
 # Install mpd
-mpd-install:
+mpd: _pkg_mgr
     # Install mpd
     sudo pacman -S mpd
     # Symlink mpd configuration
-    mkdir -p {{xdg_config_home}}/mpd
-    ln -s {{just_dir}}/mpd/mpd.conf {{xdg_config_home}}/mpd/mpd.conf
+    mkdir -p $XDG_CONFIG_HOME/mpd
+    ln -s $CONFIG_DIR/mpd/mpd.conf $XDG_CONFIG_HOME/mpd/mpd.conf
     # Create mpd data directories
     mkdir -p ~/.mpd/playlists
     # Enable and start mpd service
     sudo systemctl --user enable --now mpd
 
 # Install ncmpcpp
-ncmpcpp-install:
+ncmpcpp: _pkg_mgr
     # Install ncmpcpp
     sudo pacman -S ncmpcpp
     # Symlink ncmpcpp configuration
-    mkdir -p {{xdg_config_home}}/ncmpcpp
-    ln -s {{just_dir}}/ncmpcpp/config {{xdg_config_home}}/ncmpcpp/config
+    mkdir -p $XDG_CONFIG_HOME/ncmpcpp
+    ln -s $CONFIG_DIR/ncmpcpp/config $XDG_CONFIG_HOME/ncmpcpp/config
 
 # Install fuzzel
-fuzzel-install:
+fuzzel: _pkg_mgr
     # Install fuzzel
     sudo pacman -S fuzzel
     # Symlink fuzzel configuration
-    mkdir -p {{xdg_config_home}}/fuzzel
-    ln -s {{just_dir}}/fuzzel/fuzzel.ini {{xdg_config_home}}/fuzzel/fuzzel.ini
+    mkdir -p $XDG_CONFIG_HOME/fuzzel
+    ln -s $CONFIG_DIR/fuzzel/fuzzel.ini $XDG_CONFIG_HOME/fuzzel/fuzzel.ini
 
 # Install dunst
-dunst-install:
+dunst: _pkg_mgr
     # Install dunst
     sudo pacman -S dunst
     # Symlink dunst configuration
-    mkdir -p {{xdg_config_home}}/dunst
-    ln -s {{just_dir}}/dunst/dunstrc {{xdg_config_home}}/dunst/dunstrc
+    mkdir -p $XDG_CONFIG_HOME/dunst
+    ln -s $CONFIG_DIR/dunst/dunstrc $XDG_CONFIG_HOME/dunst/dunstrc
 
 # Install system management tools
-sys-tools-install:
+sys-tools: _pkg_mgr
     # Clipboard manager
     sudo pacman -S cliphist
     # Backlight control
@@ -130,12 +144,12 @@ sys-tools-install:
     sudo pacman -S cronie
     sudo systemctl enable --now cronie
     # Pipewire
-    just pipewire-install
+    just pipewire
     # Mesa
     sudo pacman -S mesa mesa-utils
 
 # Install and setup OpenSSH
-ssh-install:
+ssh: _pkg_mgr
     # Install OpenSSH
     sudo pacman -S openssh
     # Generate SSH key
@@ -144,24 +158,18 @@ ssh-install:
     sudo systemctl enable --now sshd
 
 # Install pipewire
-pipewire-install:
+pipewire: _pkg_mgr
     # Install pipewire and related components
     sudo pacman -S pipewire wireplumber pipewire-audio pipewire-pulse pipewire-alsa
     sudo pacman -S noise-suppression-for-voice
     # Symlink pipewire configuration
-    ln -s {{just_dir}}/pipewire {{xdg_config_home}}/pipewire
+    ln -s $CONFIG_DIR/pipewire $XDG_CONFIG_HOME/pipewire
     # Enable and start pipewire services
     sudo systemctl --user enable --now pipewire
     sudo systemctl --user enable --now pipewire-pulse
 
-# Setup fontconfig
-fontconfig:
-    # Symlink fontconfig configuration
-    mkdir -p {{xdg_config_home}}/fontconfig
-    ln -s {{just_dir}}/fontconfig/fonts.conf {{xdg_config_home}}/fontconfig/fonts.conf
-
 # Install Hyprland
-hyprland-install:
+hyprland: _pkg_mgr
     # Install terminal emulator and fonts before Hyprland
     sudo pacman -S kitty noto-fonts
     # Install Hyprland and essential tools
@@ -173,32 +181,32 @@ hyprland-install:
     # Install color picker
     sudo pacman -S hyprpicker
     # Symlink Hyprland configuration
-    mv {{xdg_config_home}}/hypr/hyprland.conf {{xdg_config_home}}/hypr/hyprland.conf.bak && for file in {{just_dir}}/hypr/*.conf; do ln -s $file {{xdg_config_home}}/hypr/$(basename $file); done
+    mv $XDG_CONFIG_HOME/hypr/hyprland.conf $XDG_CONFIG_HOME/hypr/hyprland.conf.bak && for file in $CONFIG_DIR/hypr/*.conf; do ln -s $file $XDG_CONFIG_HOME/hypr/$(basename $file); done
 
 # Install waybar
-waybar-install:
+waybar: _pkg_mgr
     # Install waybar
     sudo pacman -S waybar
     # Symlink waybar configuration
-    ln -s {{just_dir}}/waybar {{xdg_config_home}}/waybar
+    ln -s $CONFIG_DIR/waybar $XDG_CONFIG_HOME/waybar
 
 # Install user scripts
 user-scripts:
     # Symlink user scripts to ~/.local/bin
     mkdir -p ~/.local/bin
-    for script in {{just_dir}}/scripts/*.sh; do ln -s $script ~/.local/bin/$(basename $script .sh); chmod u+x $script; done
+    for script in $CONFIG_DIR/scripts/*.sh; do ln -s $script ~/.local/bin/$(basename $script .sh); chmod u+x $script; done
 
 # Install development environments
-dev-install:
+dev: _pkg_mgr
     # Rust
     sudo pacman -S rustup
     rustup default stable
     # Python
     sudo pacman -S python uv
-    just miniconda-install
+    just miniconda
 
 # Install Miniconda for Python
-miniconda-install:
+miniconda:
     # Install Miniconda
     mkdir -p ~/miniconda3
     wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
@@ -210,31 +218,31 @@ miniconda-install:
     source ~/miniconda3/bin/activate && conda config --set auto_activate false
 
 # Install catppuccin theme for Qt applications
-qt-theme-install:
+qt-theme: _pkg_mgr
     # Install Qt configuration tools
     sudo pacman -S qt5ct qt6ct kvantum
     # Download catppuccin theme for kvantum (setup theme in kvantum manager manually)
-    mkdir -p ~/.local/share
-    cd ~/.local/share && git clone https://github.com/catppuccin/Kvantum.git catppuccin-kvantum
+    mkdir -p $XDG_DATA_HOME
+    cd $XDG_DATA_HOME && git clone https://github.com/catppuccin/Kvantum.git catppuccin-kvantum
 
 # Install catppuccin theme for GTK applications
-gtk-theme-install:
+gtk-theme:
     # Download catppuccin theme for GTK
     cd ~/Downloads && git clone https://github.com/Fausto-Korpsvart/Catppuccin-GTK-Theme.git
     # Install GTK theme
     cd ~/Downloads/Catppuccin-GTK-Theme/themes && sh install.sh -l
 
 # Install catppuccin theme for system cursors
-cursor-theme-install:
+cursor-theme:
     #!/usr/bin/env sh
     theme="catppuccin-macchiato-dark"
     version="2.0.0"
-    mkdir -p ~/.local/share/icons && cd ~/.local/share/icons
+    mkdir -p $XDG_DATA_HOME/icons && cd $XDG_DATA_HOME/icons
     curl -LOsS https://github.com/catppuccin/cursors/releases/download/v${version}/${theme}-cursors.zip
     unzip ${theme}-cursors.zip && rm ${theme}-cursors.zip
 
 # Install catppuccin theme for GRUB
-grub-theme-install:
+grub-theme:
     # Download and install catppuccin theme for GRUB
     cd ~/Downloads && git clone https://github.com/catppuccin/grub.git catppuccin-grub && sudo cp -r catppuccin-grub/src/* /usr/share/grub/themes/
     # Setup theme in GRUB configuration
@@ -243,7 +251,7 @@ grub-theme-install:
     sudo grub-mkconfig -o /boot/grub/grub.cfg
 
 # Install QEMU/KVM and virt-manager
-virt-install:
+vm: _pkg_mgr
     # Install packages
     sudo pacman -S qemu-full virt-manager virt-viewer dnsmasq vde2 bridge-utils openbsd-netcat ebtables swtpm
     # Enable and start libvirt service
@@ -254,3 +262,20 @@ virt-install:
     @echo "VirtIO drivers for Windows VMs: https://fedorapeople.org/groups/virt/virtio-win"
     # (Manual step) Install SPICE Guest Tools for Windows VMs
     @echo "SPICE Guest Tools for Windows VMs: https://www.spice-space.org/download.html"
+
+# Install fonts
+font: _pkg_mgr
+    # English fonts
+    sudo pacman -S noto-fonts
+    # Chinese fonts
+    sudo pacman -S noto-fonts-cjk
+    # Symbol fonts
+    sudo pacman -S ttf-nerd-fonts-symbols noto-fonts-emoji
+    # Monospace fonts
+    sudo pacman -S ttf-jetbrains-mono
+
+# Setup fontconfig
+fontconfig:
+    # Symlink fontconfig configuration
+    mkdir -p $XDG_CONFIG_HOME/fontconfig
+    ln -s $CONFIG_DIR/fontconfig/fonts.conf $XDG_CONFIG_HOME/fontconfig/fonts.conf
